fix: cannot customize the radio container theme
chakra-ui/chakra-ui pull request #2737
Opened 2020-12-08 09:56 UTC by gifaeriyanto

Closes # 

## 📝 Description

> Now we cannot customize the radio container like the checkbox. I want to add a part named container like the checkbox, so we can customize it.

## ⛳️ Current behavior (updates)

> We cannot customize the radio container

## 🚀 New behavior

> Now we can customize the radio container

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2020-12-09 11:44 UTC, dodas requested changes
You should add `container` to the `parts` array in the theme: https://github.com/chakra-ui/chakra-ui/blob/f41a231aa7241419aa8bb4a31cca508e19a3a464/packages/theme/src/components/radio.ts#L3

2020-12-09 11:54 UTC, gifaeriyanto commented
> You should add `container` to the `parts` array in the theme:
> 
> https://github.com/chakra-ui/chakra-ui/blob/f41a231aa7241419aa8bb4a31cca508e19a3a464/packages/theme/src/components/radio.ts#L3

oh nice, I'll add it. Thanks

2020-12-09 15:56 UTC, dodas approved these changes

2020-12-10 20:29 UTC, merged

2020-12-12 17:56 UTC, ljosberinn commented
@allcontributors please add @gifaeriyanto for bug