test(avatar): added mocked image tests
chakra-ui/chakra-ui pull request #2901
Opened 2020-12-28 16:43 UTC by anuraghazra

Closes # 

## 📝 Description

Added skipped tests for Avatar image load/fail cases.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2021-01-02 18:46 UTC, TimKolberger requested changes
Thank you for this PR @anuraghazra!
I love seeing our codebase getting more bulletproof with tests ✨ 

I requested two small changes in the code. I would be happy to merge this PR when they are fixed.

2021-01-02 18:46 UTC, TimKolberger commented on packages/avatar/tests/avatar.test.tsx
> +      }
We could reduce the duplicate lines with a switch statement:

```suggestion
      setTimeout(() => {
        switch (loadState) {
          case LOAD_IMAGE:
            this.onload()
            break
          case ERROR_IMAGE:
            this.onerror()
            break
          default:
            return
        }
      }, DELAY)
```

2021-01-02 18:46 UTC, TimKolberger commented on packages/avatar/tests/avatar.test.tsx
> +const mockImage = (loadState: string) => {
There are only two allowed strings for this function, so we can use a more narrow type for `loadState`.

```suggestion
const mockImage = (loadState: "load" | "error") => {
```

2021-01-03 07:15 UTC, anuraghazra commented on packages/avatar/tests/avatar.test.tsx
> +  ;(window.Image as unknown) = class {
It was throwing "MockImage" not used eslint error so removed it.

2021-01-03 07:15 UTC, anuraghazra commented
Hi @timkindberg I've pushed the requested changes. :)

2021-01-03 11:44 UTC, TimKolberger approved these changes
🚀 thank you for your time @anuraghazra

2021-01-06 07:05 UTC, merged