fix(toast): set maxWidth on container component
chakra-ui/chakra-ui pull request #3935
Opened 2021-05-01 11:23 UTC by n1ru4l

Closes # 

## 📝 Description

I noticed that showing a toast with content that is bigger than the toast maximum width is cut-off. Instead, I expected the child elements to respect the width of the toast.

```tsx
toast({
  title: `Error while evaluating template`,
  description: (
    <Code
      overflowX="scroll"
      display="block"
      whiteSpace="pre"
      children={result.chatMessageCreate.error.reason}
    />
  ),
  status: "error",
  duration: null,
  isClosable: true,
  position: "top"
});
```

## ⛳️ Current behavior (updates)

![image](https://user-images.githubusercontent.com/14338007/116780967-1cc2db00-aa80-11eb-89cd-aee9d27fd26c.png)

No overflow-x scroll bar possible 😢 

## 🚀 New behavior

![image](https://user-images.githubusercontent.com/14338007/116780984-3ebc5d80-aa80-11eb-9b95-b6342f5f5503.png)

overflow-y is possible, as child elements cannot be bigger than the max-width of the toast ✅

## 💣 Is this a breaking change (Yes/No):

no

## 📝 Additional Information

2021-06-05 22:11 UTC, n1ru4l commented
Hey @cschroeter, is there anything further I could do to speed up the review process?

2021-06-06 17:42 UTC, TimKolberger approved these changes

2021-06-07 10:16 UTC, with-heart requested changes
Fix looks good! Happy to merge if we update the changeset so that it documents **what**, **why**, and **how**.

2021-06-07 10:16 UTC, with-heart commented on .changeset/shy-clouds-smash.md
> +limit title and description width to the width of the toast message.
```suggestion
Resolved an issue where `overflowX` couldn't be used within a toast's `title` or `description` by adding `maxWidth="100%"` to the containing `div`.
```

2021-06-08 20:54 UTC, merged