fix/editable-cannot-click-when-empty
chakra-ui/chakra-ui pull request #4409
Opened 2021-07-19 00:38 UTC by anubra266

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2021-07-19 15:31 UTC, with-heart commented
Nice dude! This seems like a solid fix!

2021-07-19 15:32 UTC, with-heart approved these changes
Nice dude! This seems like a solid fix!

2021-07-19 16:24 UTC, with-heart commented
I updated the changeset to add a bunch of additional context around the change

2021-07-20 15:29 UTC, anubra266 commented
Thanks for your review @with-heart

2021-07-21 05:02 UTC, yutaosawa81 commented
I encountered the bug just yesterday and tried the same way that adds `w="full"` to EditablePreview. It is now clickable but seems to be hard to click the EditablePreview with zero height and only padding.

![image](https://user-images.githubusercontent.com/51390769/126432873-7e2e0d0c-40e4-49e9-bb0a-b39ab394f8d7.png)

I think we can fix it by settting `height: 30px` (replace it to actually EditableInput height) to Editable and `height: 100%` to EditablePreview. Could you fix this as well? Thank you

2021-07-22 12:56 UTC, segunadebayo requested changes

2021-07-22 12:56 UTC, segunadebayo commented on packages/editable/src/use-editable.ts
> +        w: "full",
Thanks for your work here @anubra266.

I usually consider hooks like this to be agnostic of Chakra UI styling. In this case, I'll move the `w=full` to the `EditablePreview` component and pass it as a prop there.

2021-08-09 08:30 UTC, segunadebayo commented
After taking a look at this, I think this can be a user-land fix. Ideally, the user wants to specify a `placeholder` when the input is empty to prevent this.

Adding `width:100%` is making an assumption that it'll always take up the full-width when it's in the preview mode, and that doesn't feel right to me. There's also a potential (visual) breaking change possibility.

I'm going to close this and recommend that users apply a `placeholder` instead.

2021-08-09 08:30 UTC, closed without merging