feat(toast): expose Toast wrapper style prop for override
chakra-ui/chakra-ui pull request #4922
Opened 2021-10-25 19:07 UTC by karrui

Closes #4387

This PR is a continuation of #4432 since that PR seems to have been abandoned. As such, the description is copied from that original PR and extended if necessary.

## 📝 Description

When users set a fixed-width on their custom toast, this causes their toast to not be centered. This is because we set a fixed `maxWidth` property on the wrapper component around the toast, which results in the invisible wrapper being centered correctly, but the visible custom component overflowing the parent (the wrapper), making it seem off-centered.

A more detailed explanation of why this arises can be found [here](https://github.com/chakra-ui/chakra-ui/issues/4387#issuecomment-884419618)

## ⛳️ Current behavior (updates)

The div (with `class="chakra-toast__inner"`) wrapping the dispatched `Toast` component currently has a hardcoded style, causing toasts to appear off-center if its child element has a width that is higher than the hardcoded `maxWidth` of `560px`.

## 🚀 New behavior

Instead of only exposing the maxWidth prop so that that behaviour can be fixed, instead opt to expose (a new) `wrapperStyles` prop so users can freely update the hardcoded style and more.

For example, the off-center bug can be fixed with

```ts
// Via instantiation
const toast = useToast({
    position: "top",
    title: "Wrapper style is updated",
    wrapperStyle: {
      maxWidth: "100%",
    },
})

// Via trigger
<Button onClick={() => toast({ wrapperStyle: { maxWidth: "100%" } })}>
    toast
</Button>
```

## 💣 Is this a breaking change (Yes/No):

No 

## 📝 Additional Information

2021-11-05 15:56 UTC, 0x7An commented
+1 for this, overriding styles of toast are very useful.

2021-11-11 22:40 UTC, RSchneider94 commented
+2 :D are you guys planning to merge this soon? thanks!

2021-11-15 06:04 UTC, sozonome commented
+3, really appreciate it if this can be merged soon. 

Currently I'm using `react-hot-toast` when I want full screen toast

If this get merged I can remove that package and use chakra-ui's toast instead

2021-11-16 12:51 UTC, segunadebayo requested changes
Thanks for working on this @karrui. Some feedback to get this merged:

- Please rename all instances of `wrapperStyle` to `containerStyle`, I think it's more intuitive.
- Update the docs to include this feature
- Update the changeset based on my suggestion

2021-11-16 12:51 UTC, segunadebayo commented on .changeset/moody-bees-pay.md
> +exposes toast component's wrapper style prop
```suggestion

The `toast` function now exposes a `containerStyle` property you can use to
override the default styles for the toast container.

```jsx live=false
function Example() {
  const toast = useToast()
  return <button>Click me</button>
}
```
```

2021-11-16 12:51 UTC, segunadebayo commented on packages/toast/src/toast-manager.tsx
> +    | "wrapperStyle"
```suggestion
    | "containerStyle"
```

2021-11-16 12:51 UTC, segunadebayo commented on packages/toast/src/toast-manager.tsx
> +      wrapperStyle: options.wrapperStyle,
```suggestion
      containerStyle: options.containerStyle,
```

2021-11-18 12:30 UTC, karrui commented
> Thanks for working on this @karrui. Some feedback to get this merged:
> 
> * Please rename all instances of `wrapperStyle` to `containerStyle`, I think it's more intuitive.
> * Update the docs to include this feature
> * Update the changeset based on my suggestion

Done. Thanks for the review.

2021-11-22 09:03 UTC, merged