fix: thumb does not move in case of stacked thumbs
chakra-ui/chakra-ui pull request #5081
Opened 2021-11-13 06:03 UTC by burhanuday

Closes https://github.com/chakra-ui/chakra-ui/issues/5041

## 📝 Description

fixed a bug where thumb would not move in case of stacked thumbs

## ⛳️ Current behavior (updates)

The thumb does not move because the incorrect thumb is selected

## 🚀 New behavior

Fixed the index of thumb being selected

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2021-11-13 08:22 UTC, segunadebayo commented
Hi @burhanuday,

Can we write a test to cover this so we don't introduce regressions in the future?

Thank you.

2021-11-13 12:35 UTC, burhanuday commented
@segunadebayo not sure on how to emulate click on the `RangeSliderFilledTrack` component. We don't have any tests emulating clicks to start off of

2021-11-13 15:29 UTC, burhanuday commented
@segunadebayo i found the following issue - https://github.com/testing-library/testing-library-docs/issues/495 . It demonstrates an example of testing a slider with RTL but the author also states that it will only work in the browser since JSDOM does not support `getBoundingClientRect`. I dont think we can reliably test mouse interactions like drag on the slider. All our current tests on `RangeSlider` only test the keyboard related functionality. If possible, can you tag someone from the Chakra team who can help me with this?

2021-11-15 02:29 UTC, weiliao715 requested changes
The start index may not be 0
Line 363 should be "index = index + thumbsAtPosition.length - 1"

2021-11-16 10:16 UTC, merged

2021-11-16 14:09 UTC, weiliao715 commented
@segunadebayo thanks for merging.

Please check the line363 in use-range-slider.js, I think we should replace "index = thumbsAtPosition.length - 1" with "index = index + thumbsAtPosition.length - 1". It is an index increment instead of override the index value.

2021-11-16 14:42 UTC, burhanuday commented
Yes. @weiliao715 is correct. I'll make a seperate PR for this since this has been merged.

2021-12-29 17:38 UTC, weiliao715 commented
@burhanuday Please create a PR to resolve this issue, thanks.