Control whether Tooltip can be closed with Esc key
chakra-ui/chakra-ui pull request #5199
Opened 2021-12-06 09:05 UTC by mlajtos

Closes #5156 

## 📝 Description

This PR adds ability to turn off closing of the Tooltip via Esc key.

## ⛳️ Current behavior (updates)

Every Tooltip registers a `keydown` handler to listen for Esc key press. If there are a lot of the page (>1000), the performance might suffer.

## 🚀 New behavior

User can opt-out from using Esc to close Tooltip via new optional `closeOnEsc` prop that has `true` as default value to preserve current behavior.

## 💣 Is this a breaking change (Yes/No):

Yes, it adds new prop to the Tooltip API. Current users are not affected.

## 📝 Additional Information

2022-02-17 10:29 UTC, TimKolberger requested changes
Thank you for working on this @mlajtos 💖

I added a tiny comment in my review. Could you kindly add a test for this? 
If you need support with that feel free to reach out!

2022-02-17 10:29 UTC, TimKolberger commented on packages/hooks/src/use-event-listener.ts
> +      return () => {}
We can safely remove the noop function here:

```suggestion
      return
```

2022-02-21 09:32 UTC, mlajtos commented
@TimKolberger Thank you for your suggestions. What kind of test you have in mind? For `useEventListener` hook, or `closeOnEsc` prop?

2022-02-21 09:36 UTC, TimKolberger commented
I'd like to make sure that the feature "closeOnEsc" will survive refactorings.
The implementation detail "useEventListener" is not very important for me (in this case).

2022-03-15 18:06 UTC, TimKolberger approved these changes

2022-03-15 18:06 UTC, merged

2022-03-16 06:34 UTC, mlajtos commented
@TimKolberger Thank you for merging. One question though – test ran okay on my machine, but they were failing on CI. What's up with that?

2022-03-16 07:23 UTC, TimKolberger commented
An unsolved issue, could not pinpoint it yet. It mostly happens with the yarn script test:ci which uses jests runinband option, so I am guessing there is somewhere a failed mock cleanup/setup.