Allow opt-in for outline/shadow on focused elements
chakra-ui/chakra-ui pull request #5619
Opened 2022-02-18 10:22 UTC by tomhicks

Closes #5575
## 📝 Description

This will need to be documented, but ultimately this allows users to override the automatic focus style overrides applied when using focus-visible.

The focus-visible documentation suggests adding a get-out like this, so Chakra really needs to give us one!

## ⛳️ Current behavior (updates)

When using the focus-visible package, it is impossible to apply certain styles to certain focussed elements. For example, adding a shadow to a link when focussed is currently not possible.

## 🚀 New behavior

By adding a special `data-` attribute, we allow developers to opt-out of this override in certain cases.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

The focus-visible docs are slightly confusing on this. It says first:

> We suggest that users selectively disable the default focus style by selecting for the case when the polyfill is loaded and .focus-visible is not applied to the element:

with this example

```css
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}
```

Then they say:

> Alternatively, if you're using a framework which overwrites your classes ([#179](https://github.com/WICG/focus-visible/issues/179)), you can rely on the data-js-focus-visible and data-focus-visible-added attributes.

And give this example, which is what Chakra already has:

```css
[data-js-focus-visible] :focus:not([data-focus-visible-added]) {
  outline: none;
}
```

The problem is that you can't just add `data-focus-visible-added` or whatever to your element, because the focus-visible package goes around adding and removing that attribute - it can work for one render, then the attribute is removed by the library, and it's broken again.

I think their docs are wrong, or possibly just confusing. You do need an extra opt-out selector.

2022-02-18 12:57 UTC, tomhicks commented on packages/css-reset/src/css-reset.tsx
> +      [data-js-focus-visible] :focus:not([data-focus-visible-added]):not([data-chakra-allow-focus-highlights]) {
This isn't correct. This has broken the selector for the focus-visible plugin, so the reason you're seeing it "work" is that focus-visible is not working at all.

You need to add the data-chakra-allow-focus-highlights attribute to opt-out of the shadow-hiding behaviour.

Hopefully this shows it more clearly:
https://codesandbox.io/s/zealous-nobel-gw1hhh?file=/src/index.tsx

2022-03-15 18:26 UTC, TimKolberger requested changes
Thanks for creating this PR @tomhicks 💖 
I added my thoughts as comments.

2022-04-25 11:20 UTC, tomhicks commented
@TimKolberger can we get some eyes on this? I've implemented your change of selector as requested.

But this not being in the deployed package is pretty annoying because I still can't add focus styles to buttons.

2022-05-01 14:53 UTC, TimKolberger approved these changes
Thanks for working on this @tomhicks ✨

2022-05-01 14:54 UTC, merged