feat(wrap): separate v and h margins
chakra-ui/chakra-ui pull request #5772
Opened 2022-03-26 03:00 UTC by mix3d

Closes # 

## 📝 Description

> Adds the option to specify vertical and horizontal spacing options for the wrap component, should the user choose. 
> Falls back to the `spacing` prop for defaults or to set both h and v at the same time.
> Also fixes the code example of Wrap in the layout package.

## ⛳️ Current behavior (updates)

> The Wrap component adds the `spacing` prop to both horizontal and vertical margins, with no opportunity for the user to specify anything else.

## 🚀 New behavior

> Users can optionally specify `hSpacing` and/or `vSpacing` to choose a specific margin for that axis.

## 💣 Is this a breaking change (Yes/No):

No, intentionally made backwards compatible.

## 📝 Additional Information

2022-03-27 14:06 UTC, segunadebayo requested changes

2022-03-27 14:06 UTC, segunadebayo commented on packages/layout/src/wrap.tsx
> +  vSpacing?: SystemProps["margin"]
Let's change this to `spacingX` and `spacingY` to match the API in `SimpleGrid`

2022-03-27 14:06 UTC, segunadebayo commented on packages/layout/README.md
> +</Wrap>
Good catch!

2022-04-02 15:48 UTC, segunadebayo commented on packages/layout/src/wrap.tsx
> +        mapResponsive(x, (value) => tokenToCSSVar("space", value)(theme)),
```suggestion
      "--chakra-wrap-x-spacing": (theme: Dict) =>
        mapResponsive(x, (value) => tokenToCSSVar("space", value)(theme)),
      "--chakra-wrap-y-spacing": (theme: Dict) =>
        mapResponsive(y, (value) => tokenToCSSVar("space", value)(theme)),
```

2022-04-02 15:48 UTC, segunadebayo commented on packages/layout/src/wrap.tsx
> +        mapResponsive(x, (value) => tokenToCSSVar("space", value)(theme)),
It seems the x and y got mixed up here.

2022-04-02 21:25 UTC, mix3d commented on packages/layout/src/wrap.tsx
> +        mapResponsive(x, (value) => tokenToCSSVar("space", value)(theme)),
sure did. Sorry!

2022-04-04 09:02 UTC, segunadebayo approved these changes
Thanks for working through all the changes here @mix3d.

Great work 💖.

2022-04-04 09:03 UTC, merged